// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql/driver"
	"fmt"
	"time"
)

type SType string

const (
	STypeDamage       SType = "damage"
	STypeHeal         SType = "heal"
	STypeSteal        SType = "steal"
	STypeWard         SType = "ward"
	STypeCharm        SType = "charm"
	STypeGlobal       SType = "global"
	STypeManipulation SType = "manipulation"
	STypeEnchantment  SType = "enchantment"
)

func (e *SType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SType(s)
	case string:
		*e = SType(s)
	default:
		return fmt.Errorf("unsupported scan type for SType: %T", src)
	}
	return nil
}

type NullSType struct {
	SType SType
	Valid bool // Valid is true if SType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSType) Scan(value interface{}) error {
	if value == nil {
		ns.SType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SType), nil
}

type School string

const (
	SchoolFire    School = "fire"
	SchoolIce     School = "ice"
	SchoolStorm   School = "storm"
	SchoolLife    School = "life"
	SchoolMyth    School = "myth"
	SchoolDeath   School = "death"
	SchoolBalance School = "balance"
	SchoolSun     School = "sun"
	SchoolMoon    School = "moon"
	SchoolStar    School = "star"
	SchoolShadow  School = "shadow"
)

func (e *School) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = School(s)
	case string:
		*e = School(s)
	default:
		return fmt.Errorf("unsupported scan type for School: %T", src)
	}
	return nil
}

type NullSchool struct {
	School School
	Valid  bool // Valid is true if School is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSchool) Scan(value interface{}) error {
	if value == nil {
		ns.School, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.School.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSchool) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.School), nil
}

type Spell struct {
	Name        string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Cost        int32
	SpellSchool NullSchool
	Accuracy    int32
	SpellType   NullSType
}
