// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Spell struct {
	Name        string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Cost        int32
	SpellSchool string
	Accuracy    int32
	SpellType   string
}

type User struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
}
