// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: spells.sql

package database

import (
	"context"
	"time"
)

const createSpell = `-- name: CreateSpell :one
INSERT INTO spells (name, created_at, updated_at, cost, spell_school, accuracy, spell_type)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING name, created_at, updated_at, cost, spell_school, accuracy, spell_type
`

type CreateSpellParams struct {
	Name        string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Cost        int32
	SpellSchool NullSchool
	Accuracy    int32
	SpellType   NullSType
}

func (q *Queries) CreateSpell(ctx context.Context, arg CreateSpellParams) (Spell, error) {
	row := q.db.QueryRowContext(ctx, createSpell,
		arg.Name,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Cost,
		arg.SpellSchool,
		arg.Accuracy,
		arg.SpellType,
	)
	var i Spell
	err := row.Scan(
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Cost,
		&i.SpellSchool,
		&i.Accuracy,
		&i.SpellType,
	)
	return i, err
}

const deleteSpells = `-- name: DeleteSpells :exec
DELETE FROM spells
`

func (q *Queries) DeleteSpells(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteSpells)
	return err
}

const getSpell = `-- name: GetSpell :one
SELECT name, created_at, updated_at, cost, spell_school, accuracy, spell_type FROM spells
WHERE name = $1
`

func (q *Queries) GetSpell(ctx context.Context, name string) (Spell, error) {
	row := q.db.QueryRowContext(ctx, getSpell, name)
	var i Spell
	err := row.Scan(
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Cost,
		&i.SpellSchool,
		&i.Accuracy,
		&i.SpellType,
	)
	return i, err
}

const getSpells = `-- name: GetSpells :many
SELECT name, created_at, updated_at, cost, spell_school, accuracy, spell_type FROM spells
`

func (q *Queries) GetSpells(ctx context.Context) ([]Spell, error) {
	rows, err := q.db.QueryContext(ctx, getSpells)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Spell
	for rows.Next() {
		var i Spell
		if err := rows.Scan(
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Cost,
			&i.SpellSchool,
			&i.Accuracy,
			&i.SpellType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
